version: '2'

services:
    postgres:
        command: postgres
        image: postgres:latest
        container_name: micro_postgres
        environment:
            - POSTGRES_USER=kong
            - POSTGRES_DB=kong
        expose:
            - 5432
    kong:
        links:
            - postgres
        ports:
            - 8000:8000
            - 8001:8001
        image: kong:latest
        container_name: micro_kong
        environment:
            - KONG_DATABASE=postgres
            - KONG_PG_HOST=micro_postgres
            - KONG_PG_USER=kong
            - KONG_PG_PASSWORD=kong
            - KONG_PG_DATABASE=kong
        expose:
            - 8000
            - 8443
            - 8001
            - 7946